dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_install:
  - export CXX=/usr/bin/g++-8
  - export CC=/usr/bin/gcc-8
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install catch2
  - export VCPKG_ROOT=$(pwd)
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . -- -j2 
  - ctest -j2
  - ./bin/fuzzy_search_benchmark

notifications:
  email: false
