dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_script:
  - export CXX=/usr/bin/g++-8
  - export CC=/usr/bin/gcc-8
  - mkdir build
  - cd build

script:
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . -- -j2 
  - ctest -j2
  - ./bin/fuzzy_search_benchmark

notifications:
  email: false
